### ISSUE TITLE
systems/group.00 failed! error: Unable to allocate 49.6 GiB for an array with shape (6663254520,) and data type float64

### ISSUE THREAD

**Issue by xrik** [deepmodeling/deepks-kit#58]
When I try to run a 70 atom system, it reported a memory error. So I expand the original water single example system(https://github.com/deepmodeling/deepks-kit/tree/master/examples/water_single/) to help locating the problem.

20 copies of the original water_single system(simple make a 20 copies of the original water_single system):
yaml file follow the default setting : https://github.com/deepmodeling/deepks-kit/tree/master/examples/water_single/iter/args.yaml  

atom.npy:
water_single default(300, 3, 4)
20 water molecules：(400, 60, 4)
change description: I replicated 3 water atoms by 20 times. that is from 1 water molecule to 20 water molecules system; also shift  x y z by 2 unit to avoid atom overlap 
20 molecules frame like this:
 [[ 8.00000000e+00 -5.66894076e+00  2.63522653e+01  1.37552230e+01]
  [ 1.00000000e+00 -4.64473727e+00  2.62987038e+01  1.21355646e+01]
  [ 1.00000000e+00 -6.54175752e+00  2.79952980e+01  1.36818251e+01]
  ...
  [ 8.00000000e+00  3.74331059e+02  4.06352265e+02  3.93755223e+02]
  [ 1.00000000e+00  3.75355263e+02  4.06298704e+02  3.92135565e+02]
  [ 1.00000000e+00  3.73458242e+02  4.07995298e+02  3.93681825e+02]]
original 1 water molecule frame like this :
 [[ 8.00000000e+00 -5.66894076e+00  2.63522653e+01  1.37552230e+01]
  [ 1.00000000e+00 -4.64473727e+00  2.62987038e+01  1.21355646e+01]
  [ 1.00000000e+00 -6.54175752e+00  2.79952980e+01  1.36818251e+01]]

energy.npy:
water_single default:(300, 1)
20 water molecules：(400, 1)
note: no change

force.npy:
water_single default(300, 3, 3)
20 water molecules(400, 60, 3)
change description: I replicated force 20 times. No change of force value, that is 20 water molecules has the same force value
20 molecules frame like this:
  [[ 0.01365311  0.01130072 -0.03252444]
  [-0.02535562  0.00565212  0.03616008]
  [ 0.01170251 -0.01695284 -0.00363565]
  ...
  [ 0.01365311  0.01130072 -0.03252444]
  [-0.02535562  0.00565212  0.03616008]
  [ 0.01170251 -0.01695284 -0.00363565]]
original 1 water molecule frame like this :
  [[ 0.01365311  0.01130072 -0.03252444]
  [-0.02535562  0.00565212  0.03616008]
  [ 0.01170251 -0.01695284 -0.00363565]]

  
Error output:
key screening print: 
starting step: (0,)
starting step: (0, 0)
starting step: (0, 0, 0)
new submission of d5963352-3a10-4a6c-836e-281da236d34f for chunk 43ee2d12b8f2311e3a7da9df67f22ae37cf9c937
job d5963352-3a10-4a6c-836e-281da236d34f terminated, submit again
job d5963352-3a10-4a6c-836e-281da236d34f terminated, submit again
job d5963352-3a10-4a6c-836e-281da236d34f terminated, submit again

key error from err file(in folder : deepks-kit-master/examples/water_single_one/iter/iter.init/00.scf/task.trn.00):
systems/group.00 failed! error: Unable to allocate 49.6 GiB for an array with shape (6663254520,) and data type float64
Traceback (most recent call last):
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/scf/hf.py", line 1692, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/scf/hf.py", line 128, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/scf.py", line 146, in get_veff
    v0 = self.get_veff0(mol, dm, dm_last, v0_last, hermi)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/scf.py", line 112, in get_veff0
    return super().get_veff(*args, **kwargs)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/dft/rks.py", line 116, in get_veff
    vj, vk = ks.get_jk(mol, dm, hermi)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/scf/hf.py", line 2047, in get_jk
    self._eri = mol.intor('int2e', aosym='s8')
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/gto/mole.py", line 3460, in intor
    return moleintor.getints(intor, self._atm, bas, env,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/gto/moleintor.py", line 240, in getints
    return getints4c(intor_name, atm, bas, env, shls_slice, comp,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/gto/moleintor.py", line 598, in getints4c
    out = numpy.ndarray((nao_pair*(nao_pair+1)//2), buffer=out)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 49.6 GiB for an array with shape (6663254520,) and data type float64

Running command:
python -u -m deepks iterate args.yaml

my System description:
Ubuntu18 running in VMware® Workstation 15 Pro(Windows 10, 64-bit)
4 CPU core，8G memory for Ubuntu18

Install description:
created DeePKS environment using Conda and installed pytorch following this link (https://deepks-kit.readthedocs.io/en/latest/installation.html)
then install deepks by: pip install git+https://github.com/deepmodeling/deepks-kit (master branch, not abacus branch here)
 
 
---------------------
same 20 copies of water system can run correctly in deepks abacus branch, by following the setting in example/water_single_lda2pbe_abacus folder

---------------------
70 atom system:
400 frames，70 atoms，C14 H1 N12 O8 S16 , float64 type
using default setting: deepks\examples\water_single\iter\args.yaml 

Error output:
key screening print: 
/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
 starting step: (0,)
 starting step: (0, 0)
 starting step: (0, 0, 0)
 new submission of d5963352-3a10-4a6c-836e-281da236d34f for chunk 43ee2d12b8f2311e3a7da9df67f22ae37cf9c937
 job d5963352-3a10-4a6c-836e-281da236d34f terminated, submit again
 job d5963352-3a10-4a6c-836e-281da236d34f terminated, submit again
 job d5963352-3a10-4a6c-836e-281da236d34f terminated, submit again
Traceback (most recent call last):
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/__main__.py", line 11, in <module>
    main_cli()
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/main.py", line 37, in main_cli
    sub_cli(args.args)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/main.py", line 259, in iter_cli
    main(**argdict)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/iterate/iterate.py", line 351, in main
    iterate.run()
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/workflow.py", line 49, in run
    task.run(curr_tag)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/workflow.py", line 49, in run
    task.run(curr_tag)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/workflow.py", line 49, in run
    task.run(curr_tag)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/task.py", line 88, in run
    self.execute()
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/task.py", line 214, in execute
    self.dispatcher.run_jobs(tdicts, group_size=self.group_size, para_deg=self.para_deg,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/job/dispatcher.py", line 118, in run_jobs
    while not self.all_finished(job_handler, mark_failure) :
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/task/job/dispatcher.py", line 257, in all_finished
    raise RuntimeError('Job %s failed for more than 3 times' % job_uuid)
RuntimeError: Job d5963352-3a10-4a6c-836e-281da236d34f failed for more than 3 times

  
key error from err file: (deepks-kit-master/examples/water_single_one/iter/iter.init/00.scf/task.trn.00):
systems/group.00 failed! error: Unable to allocate 219. GiB for an array with shape (29416827846,) and data type float64
Traceback (most recent call last):
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/scf/hf.py", line 1692, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/scf/hf.py", line 128, in kernel
    vhf = mf.get_veff(mol, dm)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/scf.py", line 146, in get_veff
    v0 = self.get_veff0(mol, dm, dm_last, v0_last, hermi)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/deepks/scf/scf.py", line 112, in get_veff0
    return super().get_veff(*args, **kwargs)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/dft/uks.py", line 87, in get_veff
    vj, vk = ks.get_jk(mol, dm, hermi)
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/scf/uhf.py", line 902, in get_jk
    self._eri = mol.intor('int2e', aosym='s8')
  dddFile "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/gto/mole.py", line 3460, in intor
    return moleintor.getints(intor, self._atm, bas, env,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/gto/moleintor.py", line 240, in getints
    return getints4c(intor_name, atm, bas, env, shls_slice, comp,
  File "/home/manager/anaconda3/envs/deepks/lib/python3.10/site-packages/pyscf/gto/moleintor.py", line 598, in getints4c
    out = numpy.ndarray((nao_pair*(nao_pair+1)//2), buffer=out)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 219. GiB for an array with shape (29416827846,) and data type float64

**Comment by y1xiaoc** [comment]
This is because the system is too large that the eri calculation in pyscf is out of memory. Setting `incore_anyway: False` in `mol_args` in your input yaml file should fix it.

**Comment by ouqi0711** [comment]
You may specify "mf.direct_scf=True" in your scf_args. By setting mf.direct_scf=True, PySCF will not save the two-electron integral, instead it will construct the contraction of the two-electron integral with the density matrix directly.

**Comment by xrik** [comment]
> This is because the system is too large that the eri calculation in pyscf is out of memory. Setting `incore_anyway: False` in `mol_args` in your input yaml file should fix it.

worked! thanks a lot!
