### ISSUE TITLE
problems of package and function versions in the case of running a single water molecule in deepks

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/deepks-kit#81]
I have  installed deepks and abacus on my local machine. I met some problems with package and function versions in the case of running a single water molecule in deepks. Here are a few of my questions.

1. What version of pyscf is compatible with deepks? What can be done about the following problems?
/deepks-kit/examples/water_single/iter/iter.init/00.scf/task.trn.00/err:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 6, in <module>
    from pyscf import gto, lib
ModuleNotFoundError: No module named 'pyscf'
systems/group.00 failed! error: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 2000, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 175, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
systems/group.00 failed! error: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 2000, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 175, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
systems/group.00 failed! error: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 268, in <module>
    cli()
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/main.py", line 174, in scf_cli
    main(**argdict)
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 236, in main
    meta, result = solve_mol(mol, model, fields, labels,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/deepks/scf/run.py", line 52, in solve_mol
    cf.kernel()
  File "<string>", line 2, in kernel
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 2000, in scf
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/home/ps/miniconda3/envs/deepks/lib/python3.12/site-packages/pyscf/scf/hf.py", line 175, in kernel
    fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument 'fock_last'

2. Is deepks still being updated? Cause I've encountered some problems that suggest that the function or package used is old and may no longer work.
3. Is there a container image with deepks readily available on the Bohrium platform?

**Comment by y1xiaoc** [comment]
it says pyscf is not found. Have you installed it correctly? It is not in the requirement list so will not be installed automatically.

**Comment by yycx1111** [comment]
> it says pyscf is not found. Have you installed it correctly? It is not in the requirement list so will not be installed automatically.

Thank you for your answer. Yes, I have installed pyscf. I can use pyscf after a refresh. But it may be that deepks is not compatible with the pyscf version causing a TypeError: PenaltyMixin.get_fock() got an unexpected keyword argument ‘fock_last’. I stopped the error after deleting "fock_last=fock_last" from fock = mf.get_fock(h1e, s1e, vhf, dm, cycle, mf_diis, fock_last=fock_last) in pyscf/scf/hf.py.

**Comment by Peter-Goa** [comment]
I have met this issue, too. It can be solved by modifying the deepks.scf.penalty.py file. You can add "fock_last" parameter to get_fock function in that file.

**Comment by yycx1111** [comment]
> I have met this issue, too. It can be solved by modifying the deepks.scf.penalty.py file. You can add "fock_last" parameter to get_fock function in that file.

Thank you. I will try what you said！
