### ISSUE TITLE
debug in pycharm

### ISSUE THREAD

**Issue by yufengwhy** [deepmodeling/deepks-kit#9]
hi, How to debug deepks in local pycharm? Any good practice? I tried debug main.py but found many mismatch of paths

> python3 ~/Downloads/git/deepks-kit/deepks/main.py iterate ../examples/water_single/init/machines.yaml ../examples/water_single/init/params.yaml ../examples/water_single/init/systems.yaml
Traceback (most recent call last):
  File "/Users/bytedance/Downloads/git/deepks-kit/deepks/main.py", line 263, in <module>
    main_cli()
  File "/Users/bytedance/Downloads/git/deepks-kit/deepks/main.py", line 37, in main_cli
    sub_cli(args.args)
  File "/Users/bytedance/Downloads/git/deepks-kit/deepks/main.py", line 259, in iter_cli
    main(**argdict)
  File "/Users/bytedance/Downloads/git/deepks-kit/deepks/iterate/iterate.py", line 312, in main
    iterate = make_iterate(*args, **kwargs)
  File "/Users/bytedance/Downloads/git/deepks-kit/deepks/iterate/iterate.py", line 231, in make_iterate
    systems_train = collect_systems(systems_train, os.path.join(share_folder, SYS_TRAIN))
  File "/Users/bytedance/Downloads/git/deepks-kit/deepks/iterate/iterate.py", line 105, in collect_systems
    parents, bases = map(list, zip(*[os.path.split(s.rstrip(os.path.sep)) 
ValueError: not enough values to unpack (expected 2, got 0)

Process finished with exit code 1

**Comment by y1xiaoc** [comment]
You may want to ensure the example is running correctly first. It seems that you are providing some invalid parameters to the program. 

Currently I do not have a good suggestion on how to debug the whole program, due to its iterative nature. But checking each part should be relatively easy by just importing the corresponding function and examining its results on some example inputs. You may also simply add some print function in the code to see how it works.
